spring:
  application:
    name: msvc-auth

  datasource:
    url: ${AUTHDB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

msvc-users:
  url: ${MSVC_USERS_URL}


server:
  port: ${AUTH_PORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /auth-docs/v3/api-docs # Ruta personalizada para los documentos de la API
  swagger-ui:
    path: /auth-docs/swagger-ui.html # Ruta personalizada para la interfaz de Swagger UI