spring:
  application:
    name: msvc-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        # ---------------------------------------------------------------
        # Rutas para el microservicio de autenticación (msvc-auth)
        - id: auth-service
          uri: lb://msvc-auth
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authServiceCircuitBreaker
                fallbackUri: forward:/fallback/auth

        # Administración del microservicio de autenticación
        - id: auth-service-admin-routes
          uri: lb://msvc-auth
          predicates:
            - Path=/admin/**
          filters:
            - name: CircuitBreaker
              args:
                name: authServiceAdminCircuitBreaker
                fallbackUri: forward:/fallback/auth-admin

        # Microservicio de productos (msvc-books)
        - id: book-service
          uri: lb://msvc-books
          predicates:
            - Path=/api/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: bookServiceCircuitBreaker
                fallbackUri: forward:/fallback/books

        # Microservicio de usuarios (msvc-users)
        - id: user-service
          uri: lb://msvc-users
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/users

        # Microservicio de órdenes (msvc-orders)
        - id: order-service
          uri: lb://msvc-orders
          predicates:
            - Path=/api/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderServiceCircuitBreaker
                fallbackUri: forward:/fallback/orders

        # Microservicio de pagos (msvc-payments)
        - id: payment-service
          uri: lb://msvc-payments
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: paymentServiceCircuitBreaker
                fallbackUri: forward:/fallback/payments

        # ---------------------------------------------------------------
        # Rutas personalizadas para Swagger
        - id: auth-docs
          uri: lb://msvc-auth
          predicates:
            - Path=/auth-docs/**
        - id: users-docs
          uri: lb://msvc-users
          predicates:
            - Path=/users-docs/**
        - id: books-docs
          uri: lb://msvc-books
          predicates:
            - Path=/books-docs/**
        - id: orders-docs
          uri: lb://msvc-orders
          predicates:
            - Path=/orders-docs/**

  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# ---------------------------------------------------------------
# Configuración Resilience4j
resilience4j:
  circuitbreaker:
    configs:
      # Configuración predeterminada (default)
      default:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 10
        ringBufferSizeInHalfOpenState: 5
        waitDurationInOpenState: 20s
        failureRateThreshold: 40

      # Configuración específica para servicios críticos de autenticación
      authConfig:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 20
        ringBufferSizeInHalfOpenState: 10
        waitDurationInOpenState: 15s
        failureRateThreshold: 30

      # Configuración específica para servicios de pago
      paymentConfig:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 15
        ringBufferSizeInHalfOpenState: 7
        waitDurationInOpenState: 30s
        failureRateThreshold: 50

      # Configuración específica para servicios de órdenes
      ordersConfig:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 10
        ringBufferSizeInHalfOpenState: 5
        waitDurationInOpenState: 25s
        failureRateThreshold: 40

    instances:
      authServiceCircuitBreaker:
        baseConfig: authConfig
      authServiceAdminCircuitBreaker:
        baseConfig: authConfig
      bookServiceCircuitBreaker:
        baseConfig: default
      userServiceCircuitBreaker:
        baseConfig: default
      orderServiceCircuitBreaker:
        baseConfig: ordersConfig
      paymentServiceCircuitBreaker:
        baseConfig: paymentConfig
