spring:
  data:
    mongodb:
      uri: ${USERSDB_URI}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  application:
    name: msvc-users

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

server:
  port: ${USERS_PORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /users-docs/v3/api-docs
  swagger-ui:
    path: /users-docs/swagger-ui.html
