spring:
  application:
    name: msvc-payments
  datasource:
    url: ${PAYMENTDB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Cambiar según sea necesario
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
paypal:
  client-id: ${PAYPAL_CLIENT_ID}
  client-secret: ${PAYPAL_CLIENT_SECRET}
  mode: ${PAYPAL_MODE}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
    port: ${PAYMENT_PORT} #No cambiar del 8091 de puerto porque no se va a usar con el gateway

resilience4j:
  circuitbreaker:
    instances:
      payPalServiceCircuitBreaker:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 5
        ringBufferSizeInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        eventConsumerBufferSize: 10

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
