spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/usersdb
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  application:
    name: msvc-users

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8089

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /users-docs/v3/api-docs
  swagger-ui:
    path: /users-docs/swagger-ui.html
