spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${server.port}

  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    enable-self-preservation: true

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"
