spring:
  application:
    name: msvc-auth

  datasource:
    url: jdbc:postgresql://localhost:5432/UserAuth_DB
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Cambiar según sea necesario
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - email
              - profile
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            redirect-uri: ${FACEBOOK_REDIRECT_URI}
            scope:
              - email
              - profile
#        provider:
#          google:
#            issuer-uri: https://accounts.google.com
#          facebook:
#            authorization-uri: https://www.facebook.com/v10.0/dialog/oauth
#            token-uri: https://graph.facebook.com/v10.0/oauth/access_token
#            user-info-uri: https://graph.facebook.com/me?fields=id,name,email
#            user-name-attribute: id

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

msvc-users:
  url: http://msvc-users:8080


server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"
