spring:
  data:
    mongodb:
      uri: ${BOOKSDB_URI}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  application:
    name: msvc-books

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

server:
  port: ${BOOKS_PORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  api-docs:
    path: /books-docs/v3/api-docs
  swagger-ui:
    path: /books-docs/swagger-ui.html

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
