spring:
  application:
    name: msvc-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: auth-service
          uri: lb://msvc-auth
          predicates:
            - Path=/auth/**
        - id: auth-service-admin-routes
          uri: lb://msvc-auth
          predicates:
            - Path=/admin/**
        - id: book-service
          uri: lb://msvc-books
          predicates:
            - Path=/api/products/**
        - id: user-service
          uri: lb://msvc-users
          predicates:
            - Path=/users/**
        - id: order-service
          uri: lb://msvc-orders
          predicates:
            - Path=/api/orders/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
