spring:
  application:
    name: msvc-auth

  datasource:
    url: jdbc:postgresql://postgres:5432/UserAuth_DB
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

msvc-users:
  url: http://msvc-users:8080


server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /auth-docs/v3/api-docs # Ruta personalizada para los documentos de la API
  swagger-ui:
    path: /auth-docs/swagger-ui.html # Ruta personalizada para la interfaz de Swagger UI