server:
  port: 8761

spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    hostname: eureka-server
    instanceId: ${spring.application.name}:${server.port}

  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI}/eureka/

  server:
    enable-self-preservation: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
