spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/booksdb
#      auto-index-creation: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  application:
    name: msvc-books

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  api-docs:
    path: /books-docs/v3/api-docs
  swagger-ui:
    path: /books-docs/swagger-ui.html
