spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/booksdb
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  application:
    name: msvc-books

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: "*"
