server:
  port: ${NOTIFICATIONS_PORT}

spring:
  application:
    name: msvc-notifications

  # Configuración RabbitMQ
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

  # Configuración Mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

logging:
  level:
    root: INFO
    com.microservice.notifications: DEBUG

app:
  rabbitmq:
    exchange: ${EXCHANGE_NAME}
    queue: ${QUEUE_NAME}
    routingKey: ${ROUTING_KEY}

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
